// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jdrbxmtvxyzevrnoycrv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpkcmJ4bXR2eHl6ZXZybm95Y3J2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzODQ4ODQsImV4cCI6MjA2NTk2MDg4NH0.8h8wxJz-IdEBx-y5xwxDjlnzBqI48Qp_JddhQ7Rb9_8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);